language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer install

sudo: false

script:
  - ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/
  - ./vendor/bin/phpunit
