language: php

php:
  - 5.4
  - 5.5

before_script:
  - pecl -q install apc-3.1.6 && echo "extension=apc.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install

script:
  - ./vendor/bin/phpcs --standard=vendor/internations/kodierungsregelwerksammlung/ruleset.xml ./src/
  - phpunit
